joc1:
    image: harniman/jenkins-operations-center:1.609.15.1-1
    command: --prefix=""
    ports:
        - "81:8080"
    volumes:
        - ./data:/data
    links:
        - slave1
        - slave2
        - slave3
        - slave4
        - slaveDocker1
#        - elasticsearch
    environment:
        - JENKINS_HOME=/data/var/lib/jenkins/joc
    restart: always
joc2:
    image: harniman/jenkins-operations-center:1.609.15.1-1
    command: --prefix=""
    ports:
        - "82:8080"
    volumes_from:
        - joc1
    links:
        - slave1
        - slave2
        - slave3
        - slave4
        - slaveDocker1
#        - elasticsearch
    environment:
        - JENKINS_HOME=/data/var/lib/jenkins/joc
    restart: always
apiTeam1:
    image: harniman/jenkins-enterprise:1.609.15.1-1
    ports:
        - "83:8080"
    volumes_from:
        - joc1
    links:
        - ambassador:jenkins.beedemo.local
        - slave1
        - slave2
        - slave3
        - slave4
        - slaveDocker1
    environment:
        - JENKINS_HOME=/data/var/lib/jenkins/api-team
        - JENKINS_PREFIX=/api-team
    restart: always
apiTeam2:
    image: harniman/jenkins-enterprise:1.609.15.1-1
    ports:
        - "84:8080"
    volumes_from:
        - joc1
        - apiTeam1
    links:
        - ambassador:jenkins.beedemo.local
        - slave1
        - slave2
        - slave3
        - slave4
        - slaveDocker1
    environment:
        - JENKINS_HOME=/data/var/lib/jenkins/api-team
        - JENKINS_PREFIX=/api-team
    restart: always
mobileTeam1:
    image: harniman/jenkins-enterprise:1.609.15.1-1
    ports:
        - "85:8080"
    volumes_from:
        - joc1
    links:
        - ambassador:jenkins.beedemo.local
        - slave1
        - slave2
        - slave3
        - slave4
        - slaveDocker1
    environment:
        - JENKINS_HOME=/data/var/lib/jenkins/mobile-team
        - JENKINS_PREFIX=/mobile-team
    restart: always
mobileTeam2:
    image: harniman/jenkins-enterprise:1.609.15.1-1
    ports:
        - "86:8080"
    volumes_from:
        - joc1
        - mobileTeam1
    links:
        - ambassador:jenkins.beedemo.local
        - slave1
        - slave2
        - slave3
        - slave4
        - slaveDocker1
    environment:
        - JENKINS_HOME=/data/var/lib/jenkins/mobile-team
        - JENKINS_PREFIX=/mobile-team
    restart: always
#elasticsearch:
#    image: elasticsearch:1.6.1
# We need to override the command otherwise it tries to chown the data volume    
#    command: "gosu elasticsearch elasticsearch"
#    volumes:
#        - ./data/elasticsearch:/usr/share/elasticsearch/data
#    restart: always
proxy:
    image: kmadel/haproxy:1.0
    ports:
        - "80:80"
        - "9000:9000"
        - "9200:9200"
        - "4001:4001"
        - "4002:4002"
        - "4003:4003"
        - "4012:4012"
        - "4013:4013"
    expose:
        - "9200"
        - "4001"
    volumes_from:
        - joc2
        - apiTeam2
        - mobileTeam2
    volumes:
        - ./data/haproxy:/haproxy-override
    links:
#        - elasticsearch:elasticsearch
        - joc1
        - joc2
        - apiTeam1
        - apiTeam2
        - mobileTeam1
        - mobileTeam2
    restart: always
ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: -name cjpdockercompose_proxy_1
slave1:
    image: kmadel/jenkins-slave:1.0
    volumes:
        - ./data:/data
    links:
        - ambassador:jenkins.beedemo.local
    restart: always
slave2:
    image: kmadel/jenkins-slave:1.0
    volumes:
        - ./data:/data
    links:
        - ambassador:jenkins.beedemo.local
    restart: always
slave3:
    image: kmadel/jenkins-slave:1.0
    volumes:
        - ./data:/data
    links:
        - ambassador:jenkins.beedemo.local
    restart: always
slave4:
    image: kmadel/jenkins-slave:1.0
    volumes:
        - ./data:/data
    links:
        - ambassador:jenkins.beedemo.local
    restart: always
slaveDocker1:
    image: tehranian/dind-jenkins-slave
    volumes:
        - ./data:/data
    environment:
        - PORT=1234
    privileged: true
    links:
        - ambassador:jenkins.beedemo.local
    restart: always
    
